name: idid_flutter
description: Official Idid flutter plugin.
version: 5.0.0
author: Bruno Giacobo Pinto / Gabriel Manzke Lindemann / Bruno Rodrigues Bartolomasi
homepage: https://github.com/paysmart/idid_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: br.com.paysmart.idid_flutter
        pluginClass: IdidFlutterPlugin
      ios:
        pluginClass: IdidFlutterPlugin